spring.datasource.url=jdbc:postgresql://localhost:5433/telemetry
spring.datasource.username=telemetry_app
spring.datasource.password=localdevpassword
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true